package pacman.mappa;

import pacman.Costanti;
import pacman.Direction;

import java.awt.*;
import java.util.Arrays;
import java.util.Random;

public class Mappa implements Costanti {
    private final Cella[][] mappa;

    private static final Cella.TipoCella[][] mappa1 = new Cella.TipoCella[NUM_RIGHE][NUM_COLONNE];

    static {
        mappa1[0] = new Cella.TipoCella[]{Cella.TipoCella.D_ANGOLO_NO, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_ANGOLO_NE, Cella.TipoCella.D_ANGOLO_NO, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_RIGA_ORIZZ, Cella.TipoCella.D_ANGOLO_NE};
        mappa1[1] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[2] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.ANGOLO_NO, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.ANGOLO_NE, Cella.TipoCella.MELA, Cella.TipoCella.ANGOLO_NO, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.ANGOLO_NE, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.ANGOLO_NO, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.ANGOLO_NE, Cella.TipoCella.MELA, Cella.TipoCella.ANGOLO_NO, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.ANGOLO_NE, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[3] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELONE, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELONE, Cella.TipoCella.RIGA_VERT};
        mappa1[4] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.ANGOLO_SO, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.ANGOLO_SE, Cella.TipoCella.MELA, Cella.TipoCella.ANGOLO_SO, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.ANGOLO_SE, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.ANGOLO_SO, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.ANGOLO_SE, Cella.TipoCella.MELA, Cella.TipoCella.ANGOLO_SO, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.RIGA_ORIZZ, Cella.TipoCella.ANGOLO_SE, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[5] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[6] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[7] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[8] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[9] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[10] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[11] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[12] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[13] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[14] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[15] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[16] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[17] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[18] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[19] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[20] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[21] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[22] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[23] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[24] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[25] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[26] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[27] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[28] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[29] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};
        mappa1[30] = new Cella.TipoCella[]{Cella.TipoCella.RIGA_VERT, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.MELA, Cella.TipoCella.RIGA_VERT};

    }

    public Mappa() {
        //final Random rn = new Random();
        this.mappa = new Cella[NUM_RIGHE][NUM_COLONNE];
        for (int r = 0; r < NUM_RIGHE; r++) {
            for (int c = 0; c < NUM_COLONNE; c++) {
                //System.out.println(r + "-" + c);
                //System.out.println(mappa1[r][c]);
                mappa[r][c] = new Cella(c, r, mappa1[r][c] /*Cella.TipoCella.values()[rn.nextInt(7)]*/);
            }
        }
        //System.out.println(Arrays.toString(mappa[0]));
    }

    public void render(Graphics2D graphics) {
        for (Cella[] cellas : mappa) {
            //System.out.println(Arrays.toString(cellas));
            for (Cella cella : cellas) {
                cella.onRender(graphics);
            }
        }
    }

    public Cella getCella(int x, int y) {
        return mappa[y][x];
    }

    public Cella getCellaAdiacente(int x, int y, Direction dir){
        switch (dir){
            case RIGHT:
                x++;
                break;
            case LEFT:
                x--;
                break;
            case DOWN:
                y++;
                break;
            case UP:
                y--;
                break;
        }
        return mappa[y][x];
    }


}
